name: "Update repository packages"

on: 
  repository_dispatch:
    types: [build-listing]
  workflow_dispatch:
  push:
    branches: main
    paths: source.txt

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run VPM Repository Builder
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/github/workspace" \
            -w "/github/workspace" \
            --user root \
            ghcr.io/rerigferl/vpm-repository-builder:v2.0.0 \
            source.txt ${{ github.token }} repository.json
      - uses: actions/configure-pages@v5.0.0
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: website/
      - uses: actions/deploy-pages@v4.0.5
